[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/config"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.predeploy]
command = "npm run migrate"

[[services]]
name = "web"

[services.web]
source = "."
